### ISSUE TITLE
Python HSDatalog_GUI not detecting STEVAL-STWINBX1

### ISSUE THREAD

**Issue by alejandrolabajos** [STMicroelectronics/fp-sns-datalog2#16]
Hello,

I am trying to run hsdatalog_GUI.py interface on my Raspberry Pi 4 model B (64-bit). 

OS configuration:
![image](https://github.com/STMicroelectronics/fp-sns-datalog2/assets/175111274/5b8704b9-e966-4d9f-bd54-a2febb4e2449)

I followed the instructions explained in README_Linux file, located at /Utilities/HSDPython_SDK:
![image](https://github.com/STMicroelectronics/fp-sns-datalog2/assets/175111274/0835c3b8-7cae-450f-855b-c452b4d4a205)

Everything works fine during installation, including PySide6 package. 

The problem comes up when I try to run hsdpython_GUI.py, which is not detecting my STWINBX1 device.
![image](https://github.com/STMicroelectronics/fp-sns-datalog2/assets/175111274/52d92bbd-8f7a-41c7-b76e-488b9f007550)

The board is detected correctly using lsusb:
![1-lsusb](https://github.com/STMicroelectronics/fp-sns-datalog2/assets/175111274/1cf9db53-a7cb-4c75-80c2-d2cad06dd937)

Output of terminal: 
![2-terminalError](https://github.com/STMicroelectronics/fp-sns-datalog2/assets/175111274/3b3cf7fd-7b76-439f-bbf0-4da23cb654c6)

Output Logs of GUI:
![3-GUI_Logs](https://github.com/STMicroelectronics/fp-sns-datalog2/assets/175111274/baa320c6-2dc4-4282-8fa8-43e8096dacd8)

I also tried to use the library provided in /Utilities/cli_example/bin_raspberryPi4_64, but as reported in Issue #15 , seems there is some problem with this lib for aarch64 64-bit OS. 

- I am not able to use this GUI with RPI 32-bit OS since there is not support of PySide6.
- Is running perfectly on my Windows 11 host PC.

Any help will be appreciated.

**Comment by pradolis** [comment]
Hello @alejandrolabajos 
I'm testing your setup in v2.2.0 and it is working. 
Pi4 has a limited RAM and USB capabilities, so we are still facing some video latency while logging many data.
Pi5 instead seems working better.

Remember that FP-SNS-DATALOG2 is not exposing datalog GUI natively in Raspberry PI installers. GUI is fully tested and intended for Windows and Linux PC only. That's why Raspberry installer setups automatically the "no_GUI" environment only. Furthermore, 32bit RPI OS is not supported.
To make "GUI" running, you must do some further manual steps (as you described), thus generating potential issues.

Is the issue systematic? Can you reboot the Raspberry once you face the issue and check how it works?

Best regards
Simone

**Comment by alejandrolabajos** [comment]
Hi @pradolis 
 
yes, same error every time and same logs

**Comment by pradolis** [comment]
Hello @alejandrolabajos 
I've just pushed the v2.2.0. Can you check the new release in your environment?

Best regards
Simone

**Comment by pradolis** [comment]
Hello @alejandrolabajos 
No further news on the topic, so I'm closing the issue.
Feel free to reopen the issue if needed.

Best regards
Simone

**Comment by alejandrolabajos** [comment]
Hi @pradolis, 

I just checked the version 2.2.0 with configuration and mlc setup provided at #19 and everything is working perfectly on my RPI4B (64-bit OS).

Thank you so much for your effort and support!!
Alex
